// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191109142957_InitialDbCreation")]
    partial class InitialDbCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("GameEngine.GameSettings", b =>
                {
                    b.Property<int>("GameSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(6);

                    b.Property<int>("BoardWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(7);

                    b.Property<string>("GameName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255)
                        .HasDefaultValue("Connect 4");

                    b.Property<string>("SaveName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("SerializedBoard")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.HasKey("GameSettingsId");

                    b.ToTable("GameSettingses");
                });
#pragma warning restore 612, 618
        }
    }
}
